0|Catppuccin-Mocha|~/.config/swww/Catppuccin-Mocha/rain_world1.png
0|Catppuccin-Latte|~/.config/swww/Catppuccin-Latte/jormungandr.jpg
0|Decay-Green|~/.config/swww/Decay-Green/moments_before_desk.png
0|Rose-Pine|~/.config/swww/Rose-Pine/japan_mountain_pink.jpg
0|Tokyo-Night|~/.config/swww/Tokyo-Night/tokyo_pink.png
0|Material-Sakura|~/.config/swww/Material-Sakura/material_pastel_4.jpg
1|Graphite-Mono|~/.config/swww/Graphite-Mono/cat_lofi_cafe.jpg
0|Cyberpunk-Edge|~/.config/swww/Cyberpunk-Edge/david.jpg
0|Frosted-Glass|~/.config/swww/Frosted-Glass/lake_mountain.jpg
0|Gruvbox-Retro|~/.config/swww/Gruvbox-Retro/street.png
