0|Catppuccin-Mocha|~/.config/swww/Catppuccin-Mocha/forest_dark_winter.jpg
1|Catppuccin-Latte|~/.config/swww/Catppuccin-Latte/lamb.jpg
0|Decay-Green|~/.config/swww/Decay-Green/moments_before_desk.png
0|Rose-Pine|~/.config/swww/Rose-Pine/waifu_pink.png
0|Tokyo-Night|~/.config/swww/Tokyo-Night/tokyo_pink.png
0|Material-Sakura|~/.config/swww/Material-Sakura/material_pastel_7.jpg
0|Graphite-Mono|~/.config/swww/Graphite-Mono/lamb-title.jpg
0|Cyberpunk-Edge|~/.config/swww/Cyberpunk-Edge/cyberpunk_dave.png
0|Frosted-Glass|~/.config/swww/Frosted-Glass/min_forest.jpg
0|Gruvbox-Retro|~/.config/swww/Gruvbox-Retro/lady.png
0|Sunrise-Dark|~/.config/swww/Sunrise-Dark/focal-fossa.png
0|WhiteSur|~/.config/swww/WhiteSur/BigSur-Tree.jpg
0|WhiteSur-Dark|~/.config/swww/WhiteSur-Dark/BigSur-Rocks-Night.jpg
