#!/usr/bin/env sh

ScrDir=$(dirname "$(realpath "$0")")
. $ScrDir/globalcontrol.sh
CAVA_CONF="${ConfDir}/cava/config"
WALL_DCOL="${ConfDir}/cava/Wall-Dcol"
KEY_LINE='### HYPRDOTS CAVA: Autogenerated line below ###'

if command -v cava &>/dev/null; then

sed -i "/${KEY_LINE}/,\$d" "${CAVA_CONF}"
if grep -q "${KEY_LINE}" "${CAVA_CONF}"; then sed -i "/${KEY_LINE}/r ${WALL_DCOL}" "${CAVA_CONF}"
else echo "${KEY_LINE}" >> "${CAVA_CONF}" ; sed -i "/${KEY_LINE}/r ${WALL_DCOL}" "${CAVA_CONF}"
fi

pkill -USR2 cava

fi
