name:
  .trash: 
  .cargo: 󱣘
  .emacs.d: 
  a.out: 
extension:
  go: 
  hs: 
  rs: 
  lua: 
  md: 
  pdf: 
  png: 
filetype:
  dir: 
  file: 
  pipe: 󰟥
  socket: 󰐧
  executable: 
  symlink-dir: 
  symlink-file: 
  device-char: 
  device-block: 󰜫
  special: 
